db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=camunda
    - POSTGRES_USER=camunda
  ports:
    - "5432:5432"
  volumes:
    - ../sql/create/postgres_engine_7.3.0.sql:/docker-entrypoint-initdb.d/0_postgres_engine_7.3.0.sql
    - ../sql/create/postgres_identity_7.3.0.sql:/docker-entrypoint-initdb.d/1_postgres_identity_7.3.0.sql

wildfly:
  image: camunda/camunda-bpm-platform:wildfly-7.3.0
  environment:
    - DB_DRIVER=postgresql
    - DB_URL=jdbc:postgresql://db:5432/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
    - TZ=Europe/Warsaw
  links:
    - db:db
  ports:
    - "8080:8080"

tomcat:
  image: camunda/camunda-bpm-platform:tomcat-7.3.0
  environment:
    - DB_DRIVER=org.postgresql.Driver
    - DB_URL=jdbc:postgresql://db:5432/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
  links:
    - db:db
  ports:
    - "8081:8080"
