db:
  image: mariadb:10.1
  environment:
    - MYSQL_ROOT_PASSWORD=camunda
    - MYSQL_DATABASE=camunda
    - MYSQL_USER=camunda
    - MYSQL_PASSWORD=camunda
  ports:
    - "3306:3306"
  volumes:
    - ../sql/create/mysql_engine_7.4.0.sql:/docker-entrypoint-initdb.d/0_mysql_engine_7.4.0.sql
    - ../sql/create/mysql_identity_7.4.0.sql:/docker-entrypoint-initdb.d/1_mysql_identity_7.4.0.sql

bpm0:
  image: camunda/camunda-bpm-platform:wildfly-7.4.0
  environment:
    - DB_DRIVER=mysql
    - DB_URL=jdbc:mysql://db:3306/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
    - TZ=Europe/Warsaw
  links:
    - db:db
  ports:
    - "8080:8080"
