db:
  image: postgres:9
  environment:
    - POSTGRES_PASSWORD=camunda
    - POSTGRES_USER=camunda

bpm0:
  image: camunda/camunda-bpm-platform:wildfly-7.3.0
  environment:
    - DB_DRIVER=postgresql
    - DB_URL=jdbc:postgresql://db:5432/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
  links:
    - db:db
  ports:
    - "8080:8080"
