db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=camunda
    - MYSQL_DATABASE=camunda
    - MYSQL_USER=camunda
    - MYSQL_PASSWORD=camunda

bpm0:
  image: camunda/camunda-bpm-platform:wildfly-7.3.0
  environment:
    - DB_DRIVER=mysql
    - DB_URL=jdbc:mysql://db:3306/camunda
    - DB_USERNAME=camunda
    - DB_PASSWORD=camunda
  links:
    - db:db
  ports:
    - "8080:8080"
